# Generated by Django 4.0.4 on 2022-05-27 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppJuegos', '0003_cargarlistadejuegos'),
    ]

    operations = [
        migrations.CreateModel(
            name='trucos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('juego', models.CharField(max_length=40)),
                ('codigo', models.CharField(max_length=40)),
                ('accion', models.CharField(max_length=40)),
            ],
        ),
    ]
